version: '2'
services:
    mred-app:
        image: mred
        external_links:
            - mred-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mred
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mred-postgresql:
        extends:
            file: postgresql.yml
            service: mred-postgresql
